---
- name: Create VLANs
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Create VLAN 10
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: USERS
          - vlan_id: 20
            name: SERVERS
        state: merged
